<?php

/**
 * Implementation of hook_menu
 * @return array
 */
function rbkc_dact_menu() {
  $items = array();

  $items['admin/structure/types/per_domain'] = array(
    'title' => 'Domain content types',
    'description' => 'Configure which content types are shown in the create-content list',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rbkc_dact_content_types'),
    'access arguments' => array('administer domain content types'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function rbkc_dact_permission() {
  $permissions = array(
    'administer domain content types' => array(
      'title' => t('Administer domain content types'),
      'restrict access' => TRUE,
    ),
  );

  return $permissions;
}


function rbkc_dact_content_types() {

  $form = array();

  $options = array();
  $types = node_type_get_types();
  foreach ($types as $type) {
    $options[$type->type] = $type->name;
  }

  $domain = domain_get_domain();

  $form['rbkc_dact_enabled_content_types'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Content types to enable for this site, '.$domain['sitename']),
    '#default_value' => domain_conf_variable_get($domain['domain_id'], 'rbkc_dact_enabled_content_types'),
    '#options' => $options,
    '#description' => t("Select the content types to enable for this site. Editors will only be able to create content that are enable here."),
  );

  $form['rbkc_dact_display'] = array(
    '#type' => 'fieldset',
    '#title' => 'Current settings',
  );

  foreach (domain_domains() as $domain) {

    $domain_content_types = domain_conf_variable_get($domain['domain_id'], 'rbkc_dact_enabled_content_types');
    $domain_content_list = array();
    $sitename = $domain['sitename'];

    foreach($domain_content_types as $content_type) {
      if ($content_type) {
        $domain_content_list[] = node_type_get_name($content_type);
      }
    }

    $domain_content_list = theme('item_list', array(
      'items' => $domain_content_list,
      'title' => $sitename,
    ));

    $form['rbkc_dact_display']['rbkc_dact_' . $domain['sitename']] = array(
      '#markup' => $domain_content_list,
    );
  }

  return system_settings_form($form);
}


/**
 * Implementation of hook_menu_alter
 * @param $items
 */
function rbkc_dact_menu_alter(&$items) {
  if (isset($items['admin/workbench/create'])) {
    $items['admin/workbench/create']['page callback'] = 'rbkc_dact_workbench_create';
  }
}


function rbkc_dact_workbench_create() {
  $output = array();
  $output['workbench_create_default'] = _rbkc_dact_workbench_create();

  // Allow other modules to add content here.
  drupal_alter('workbench_create', $output);

  return $output;
}


function _rbkc_dact_workbench_create() {
  $output = array();
  $output['#markup'] = '<h3>' . t('Create content') . '</h3>';

  $content = rbkc_dact_get_domain_content_types();

  if (!empty($content)) {
    // Theme the array of content type creation links.
    $output['#markup'] .= theme('node_add_list', array('content' => $content));
  }
  else {
    $output['#markup'] .= t('You cannot create any new content on this site. Please contact the site administrator.');
  }

  return $output;
}


function rbkc_dact_get_domain_content_types() {

  $domain = domain_get_domain();
  $enabled_types = domain_conf_variable_get($domain['domain_id'], 'rbkc_dact_enabled_content_types');
  $enabled_types = array_keys(array_filter($enabled_types));

  $all_types = node_type_get_types();

  $content = array();
  foreach ($all_types as $type_name => $type_data) {
    if (in_array($type_name, $enabled_types)) {
      $content[] = array(
        'title' => $type_data->name,
        'href' => 'node/add/'.$type_name,
        'description' => t($type_data->description),
        'localized_options' => array('attributes' => array(), 'html' => true),
      );
    }
  }

  return $content;
}

